### ISSUE TITLE
Reads can go to wrong place in multi-threaded environment

### ISSUE THREAD

**Issue by goodgravy** [teespring/active_record_replica#20]
### Environment
* Ruby 2.4.5p335
* Active Record Slave 1.6.0

### Expected Behavior
The current state of Active Record Slave (e.g. whether we should be reading from master or the slave) is transferred from one thread to another when a new thread is created. For example, in a multi-threaded Rails server where only one thread runs the initializer code, all the child threads should behave as the initializer specifies.

### Actual Behaviour
I found this limitation in Sidekiq, and I suspect #19 is related, however the behaviour can be seen in a plain irb session. Specifically, the Active Record Slave state is thread local:

```
[1] pry(main)> ActiveRecordSlave.read_from_master!
=> :master
[2] pry(main)> puts "In main thread: #{Thread.current.thread_variable_get(:active_record_slave).inspect}"
In main thread: :master
=> nil
[3] pry(main)> Thread.new { puts "In child thread: #{Thread.current.thread_variable_get(:active_record_slave).inspect}" }.join
In child thread: nil
```

As this is a fairly fundamental design decision, I don't know if there's going to be a solution here… Do you have any suggestions for how we can use Active Record Slave with e.g. Puma and Sidekiq?

**Comment by reidmorrison** [comment]
`ActiveRecordSlave.read_from_master!` is designed to only affect the current thread and not to affect that setting on any other thread. Per its comment:
https://github.com/rocketjob/active_record_slave/blob/468c7b8eb148b6694428891481db0b09143559b5/lib/active_record_slave/active_record_slave.rb#L106

The above behavior is relied upon by code elsewhere in the gem:
https://github.com/rocketjob/active_record_slave/blob/468c7b8eb148b6694428891481db0b09143559b5/lib/active_record_slave/active_record_slave.rb#L46

I suspect what you are looking for is it to use a class variable so that all threads will not read from master. Turning off all reads to slaves is achieved by removing the slave entry from the database.yml file. It can be easily done with some ERB code.

**Comment by reidmorrison** [comment]
Ah, read_from_master! is supposed to be a global and not thread specific variable.
